### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [46]:
# code
import numpy as np

a = np.random.randint(1,100,15)
a

array([66, 58, 90, 37, 77, 94, 84,  2, 87, 54, 96, 62, 24, 23, 53],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[20, 82, 78, 95],
       [21, 28, 99, 98],
       [ 9,  7, 42, 95],
       [88, 91, 72, 39],
       [64, 81, 38, 15],
       [86, 14, 43, 62]], dtype=int32)

In [11]:
np.sort(a)[::-1] #kind - will change the algoritham

array([86, 85, 84, 83, 80, 59, 46, 43, 24, 24, 20, 19, 19, 14,  2],
      dtype=int32)

In [ ]:
np.sort(b,axis=0)[::-1] #0 - means row and 1 means column 

array([[88, 91, 99, 98],
       [86, 82, 78, 95],
       [64, 81, 72, 95],
       [21, 28, 43, 62],
       [20, 14, 42, 39],
       [ 9,  7, 38, 15]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [45]:
# code
x = np.append(a,200)
x

array([ 46,   0,   0,  24,   2,  43,  14,   0,  19,   0,  20,  24,   0,
        19,   0, 200])

In [24]:
y = np.append(b,np.ones((1,b.shape[1])),axis = 0)
y

array([[20., 82., 78., 95.],
       [21., 28., 99., 98.],
       [ 9.,  7., 42., 95.],
       [88., 91., 72., 39.],
       [64., 81., 38., 15.],
       [86., 14., 43., 62.],
       [ 1.,  1.,  1.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [25]:
# code

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
# np.concatenate((c,d),axis = 0) # with column
np.concatenate((c,d),axis = 1) # with row

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [30]:
# code

e = np.array([1,1,12,2,2,3,4,5,5])
np.unique(e)

array([ 1,  2,  3,  4,  5, 12])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [34]:
# code

a.shape

(15,)

In [35]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [37]:
np.expand_dims(a,axis = 1)

array([[46],
       [84],
       [80],
       [24],
       [ 2],
       [43],
       [14],
       [83],
       [19],
       [59],
       [20],
       [24],
       [86],
       [19],
       [85]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [44]:
a

array([46,  0,  0, 24,  2, 43, 14,  0, 19,  0, 20, 24,  0, 19,  0],
      dtype=int32)

In [47]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  4,  5,  6,  8,  9, 10, 11, 14]),)

In [48]:
# replace all values > 50 with 0
# a[np.where(a>50)] = 0
# a

np.where(a>50,0,a)


array([ 0,  0,  0, 37,  0,  0,  0,  2,  0,  0,  0,  0, 24, 23,  0],
      dtype=int32)

In [49]:
np.where(a%2==0,0,a)

array([ 0,  0,  0, 37, 77,  0,  0,  0, 87,  0,  0,  0,  0, 23, 53],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [59]:
# code

np.argmax(b,axis= 0)
np.argmax(b,axis= 1)

array([3, 2, 3, 1, 1, 0])

In [61]:
b

array([[20, 82, 78, 95],
       [21, 28, 99, 98],
       [ 9,  7, 42, 95],
       [88, 91, 72, 39],
       [64, 81, 38, 15],
       [86, 14, 43, 62]], dtype=int32)

In [60]:
np.argmin(b,axis= 0)

array([2, 2, 4, 4])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [64]:
np.cumsum(a)

array([ 66, 124, 214, 251, 328, 422, 506, 508, 595, 649, 745, 807, 831,
       854, 907])

In [65]:
np.cumsum(b,axis = 1) #sum of the number 

array([[ 20, 102, 180, 275],
       [ 21,  49, 148, 246],
       [  9,  16,  58, 153],
       [ 88, 179, 251, 290],
       [ 64, 145, 183, 198],
       [ 86, 100, 143, 205]])

In [68]:
# np.cumprod

np.cumprod(b,axis = 1)

array([[      20,     1640,   127920, 12152400],
       [      21,      588,    58212,  5704776],
       [       9,       63,     2646,   251370],
       [      88,     8008,   576576, 22486464],
       [      64,     5184,   196992,  2954880],
       [      86,     1204,    51772,  3209864]])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [69]:
a

array([66, 58, 90, 37, 77, 94, 84,  2, 87, 54, 96, 62, 24, 23, 53],
      dtype=int32)

In [ ]:
np.percentile(a,100) #maximum number

np.float64(96.0)

In [ ]:
np.percentile(a,0) #minimum number 

np.float64(2.0)

In [73]:
np.percentile(a,50) #median number 
np.median(a)

np.float64(62.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [77]:
# code

np.histogram(a,bins = [0,50,100])

(array([ 4, 11]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([10,20,30,40,50])
exp=np.array([1,2,0,4,5])

np.corrcoef(salary,exp)#[       salary,exp
                       #salary    1     1
                       #exp       1     1]

array([[1.        , 0.76249285],
       [0.76249285, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [81]:
# code

x = np.array([1,2,3,4])

a[np.isin(a,x)]

array([2], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code

np.flip(a) #reverse the array but shape remain the same

array([53, 23, 24, 62, 96, 54, 87,  2, 84, 94, 77, 37, 90, 58, 66],
      dtype=int32)

In [83]:
a

array([66, 58, 90, 37, 77, 94, 84,  2, 87, 54, 96, 62, 24, 23, 53],
      dtype=int32)

In [84]:
b

array([[20, 82, 78, 95],
       [21, 28, 99, 98],
       [ 9,  7, 42, 95],
       [88, 91, 72, 39],
       [64, 81, 38, 15],
       [86, 14, 43, 62]], dtype=int32)

In [87]:
# np.flip(b) #this will do both the fliping
# np.flip(b,axis = 0)#column wise fliping
np.flip(b,axis = 1)#column wise fliping


array([[95, 78, 82, 20],
       [98, 99, 28, 21],
       [95, 42,  7,  9],
       [39, 72, 91, 88],
       [15, 38, 81, 64],
       [62, 43, 14, 86]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [88]:
# code
a

array([66, 58, 90, 37, 77, 94, 84,  2, 87, 54, 96, 62, 24, 23, 53],
      dtype=int32)

In [ ]:
np.put(a,[1,10],[110,530]) #this will permanent change the array
a

array([ 66, 110,  90,  37,  77,  94,  84,   2,  87,  54, 530,  62,  24,
        23,  53], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [115]:
# code
a = np.arange(4).reshape(2,2)
print(a)
np.delete(a,[(0,2)])
#provide the list of the data output 

[[0 1]
 [2 3]]


array([1, 3])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [101]:
a = np.array([1,2])
b = np.array([1,4])

np.union1d(a,b)

array([1, 2, 4])

In [98]:
np.intersect1d(a,b)

array([], dtype=int64)

In [ ]:
np.setdiff1d(b,a) #jo item b me he but a me nahi he b C/ a

array([4])

In [ ]:
np.setxor1d(a,b) #remove the common of both of the set

array([2, 4])

In [ ]:
np.isin(a,b) #wheather a is in b or not

array([ True, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [108]:
# code
a = np.arange(20)

In [ ]:
np.clip(a,a_min = 5,a_max = 15) #less than a_min changed to a_min and greater than a_max replased with a_max

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 15,
       15, 15, 15])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals