In [ ]:
import numpy as np  

In [ ]:
#creating a Array
list = [1,2,3,4,5]
arr = np.array(list)

In [10]:
list = [[1,2,3],[4,5,6]]

In [19]:
arr2D = np.array(list)

In [17]:
print(type(arr2D))

<class 'numpy.ndarray'>


In [ ]:
#Checking Array Properties

In [25]:
arr2D.shape
arr2D.ndim
arr2D.size
arr2D.dtype

dtype('int64')

In [26]:
#Creating Special Arrays
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
x = np.eye(4)

In [93]:
x[1][1]

np.float64(1.0)

In [33]:
np.full((2, 2), 5) 

array([[5, 5],
       [5, 5]])

In [ ]:
#Generating Ranges of Numbers

np.arange(0,10,1) #0 to 9 value with 1 of difference

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 1, 5)#0 to 9 value with 1 of difference

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
#Random Number Generation
np.random.rand(2,2,2,2)

array([[[[0.35323381, 0.30402628],
         [0.72860662, 0.90189215]],

        [[0.27089654, 0.25007016],
         [0.28742772, 0.41381517]]],


       [[[0.32315353, 0.79011193],
         [0.79827157, 0.63916545]],

        [[0.53187299, 0.54223203],
         [0.24118041, 0.76776725]]]])

In [46]:
np.random.randn(3, 3)

array([[-2.1392028 ,  1.56898079,  1.40389825],
       [-0.06885369, -0.03772305, -2.45016343],
       [ 0.2127602 ,  0.79831295,  0.80977786]])

In [47]:
np.random.randint(1, 10, (2, 3)) 

array([[2, 9, 1],
       [5, 3, 1]], dtype=int32)

In [ ]:
#Indexing and Slicing

In [48]:
arr = np.array([10, 20, 30, 40, 50])

In [54]:
arr[0:4:2]

array([10, 30])

In [55]:
arr2D[1, 2]

np.int64(6)

In [56]:
arr2D[:, 2]

array([3, 6])

In [63]:
# Mathematical Operations
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])


In [60]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [64]:
np.sum(arr)

np.int64(30)

In [65]:
np.mean(arr)

np.float64(3.0)

In [66]:
np.std(arr) 

np.float64(1.4142135623730951)

In [67]:
np.var(arr)

np.float64(2.0)

In [68]:
np.max(arr)

np.int64(5)

In [70]:
np.argmax(arr)

np.int64(4)

In [76]:
#Reshaping and Transposing
arr = np.arange(0, 10).reshape(5,2)

In [80]:
arr.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [78]:
arr.flatten() 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
#Stacking and Splitting

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [84]:
np.hstack((arr1,arr2))
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [87]:
#Linear Algebra
A = np.array([[1, 0], [0, 1]])
B = np.array([[5, 6], [7, 8]])

In [88]:
np.dot(a=A,b=B)

array([[5, 6],
       [7, 8]])

In [90]:
np.linalg.det(B)

np.float64(-2.000000000000005)

In [91]:
np.linalg.inv(B)

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [92]:
np.linalg.eig(B) 

EigResult(eigenvalues=array([-0.15206735, 13.15206735]), eigenvectors=array([[-0.75868086, -0.59276441],
       [ 0.65146248, -0.80537591]]))