In [1]:
import pickle
import numpy as np

In [2]:
# Step 1-> Import all the model with the pickle 

ohe_sex = pickle.load(open('models/ohe_sex.pkl',  'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
olf = pickle.load(open('models/clf.pkl','rb'))

In [3]:
# Step 2 -> Take the Input

test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [5]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))#Only accept the single input column data

c:\Users\axitk\anaconda3\envs\Machinelearning_new\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))#Only accept the single input column data

In [7]:
test_input_embarked

array([[0., 0., 1.]])

In [8]:
test_inpur_age = test_input[:,2].reshape(1,1)
test_transformed_data = np.concatenate((test_input[:,[0,3,4,5]],test_inpur_age,test_input_sex,test_input_embarked),axis=1)

In [9]:
test_transformed_data

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [10]:
olf.predict(test_transformed_data)

array([1])