In [1]:
import numpy as np

In [2]:
a = np.array([[1,16,3,10,5],
              [1,2,3,5,7]])
a

array([[ 1, 16,  3, 10,  5],
       [ 1,  2,  3,  5,  7]])

In [3]:
a.sum(axis=1) #axis 1 will give me the answer row wise and 0 will give answer column wise

array([35, 18])

In [4]:
dir(np); #this will give the function available in the numpy

In [11]:
%%timeit
np.sort(a,axis=1,kind='mergesort')

2.48 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
%%timeit
np.sort(a,axis=1,kind='quicksort')

2.44 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
%%timeit
np.sort(a,axis=1,kind='heapsort')

2.49 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
%%timeit
np.sort(a,axis=1,kind='stable')

2.58 µs ± 344 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
%%timeit
np.sort(a,axis=1)

2.47 µs ± 215 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
b = a[0][1:3].copy()
print(b)
b[1] = 10
print(b)
a

[16  3]
[16 10]


array([[ 1, 16,  3, 10,  5],
       [ 1,  2,  3,  5,  7]])