In [1]:
import numpy as np

# Creating a array which will work like a matrix in data science for engineering

In [2]:
a = np.array([2,1,3,4,5])
print(type(a)) # find the type of the a

<class 'numpy.ndarray'>


In [3]:
a.shape # find the shape of 

(5,)

In [4]:
a.dtype # find the shape of  data 

dtype('int32')

# Creating some value array

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.zeros((4,4)) # Creating matrix with null value

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((4,4))@np.ones((4,1)) #creating a matrix and then done multiplication

array([[4.],
       [4.],
       [4.],
       [4.]])

In [8]:
np.empty((4,5)) #this will just allocate the memory of the array will not assisgn the value 

array([[1.11980582e-311, 5.48412867e-322, 0.00000000e+000,
        0.00000000e+000,             nan],
       [1.16095484e-028, 3.94648786e+180, 2.09603059e-110,
        7.49232601e+247, 9.38293071e-154],
       [7.36093975e+223, 2.17436711e+243, 2.34728885e+251,
        3.94659409e+180, 2.21002231e+214],
       [7.79952706e-143, 2.91237123e+257, 4.71294503e+257,
        2.60025117e-306, 1.25160617e-308]])

In [ ]:
#airithmatic operation + - * / this will create a element wise everything

In [9]:
a**a (element wise a^a)

array([   4,    1,   27,  256, 3125])

In [13]:
a

array([2, 1, 3, 4, 5])

In [16]:
a[0:1] #you need to observe that when [a:b] start from a and go till the location of b-1

array([2])