**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [18]:
#Code here
x = np.zeros(10) 
x[::5] = 1
x

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [15]:
a = np.nan*np.empty(10)
a[::5] = 1
a

array([ 1., nan, nan, nan, nan,  1., nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [26]:
a = int(input("Enter the Number a: "))
b = int(input("Enter the Number b: "))

x = np.random.random((a,b))*100
print(x)

print('Average of the array {}'.format(np.average(x)))

[[12.79728492 48.99784237 37.10119354]
 [ 9.91263091 35.43317173 97.82927402]
 [69.48332019 29.50284914 75.10311634]]
Average of the array 46.24007590616042


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [31]:
row = 4
col = 4
x = np.zeros((row,col))

for i in range(0,row):
    for j in range(0,col):
        if i == 0 or j == 0:
            x[i][j] = 1
        elif i == row-1 or j == col-1:
            x[i][j] = 1
print(x)        

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [16]:
a = np.ones((4,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [17]:
np.linspace(0.01,1,12)[1:-1]

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [19]:
# No
np.eye(4)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [29]:
np.linspace(0,4,25,dtype=float).reshape((5,5))

array([[0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667],
       [0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ],
       [1.66666667, 1.83333333, 2.        , 2.16666667, 2.33333333],
       [2.5       , 2.66666667, 2.83333333, 3.        , 3.16666667],
       [3.33333333, 3.5       , 3.66666667, 3.83333333, 4.        ]])

In [23]:
z = np.zeros((5,5))
z+= np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [46]:
x = np.random.randint(1,101,size=(10,2))
p = np.array([2,3])
l = []

for i in x:
    # print(i[0])
    d = ((((i[0]-p[0])**2) + ((i[1]-p[1])**2))**0.5)
    l.append(d)
    
print('Value of the Random Point',x)   
print('Value of the Point',p)   

d = np.array(l).reshape((10,1))
d

Value of the Random Point [[99 55]
 [ 1 28]
 [39 33]
 [75 96]
 [12 40]
 [48 69]
 [12 11]
 [55  1]
 [24 38]
 [28 52]]
Value of the Point [2 3]


array([[110.05907505],
       [ 25.01999201],
       [ 47.63402146],
       [118.22859214],
       [ 38.32753579],
       [ 80.44874144],
       [ 12.80624847],
       [ 53.03772242],
       [ 41.34005322],
       [ 55.47071299]])

In [26]:
x = np.random.randint(1,101,size=(10,2))
p = np.array([2,3])
np.sqrt(np.sum((x-p)**2,axis = 1)).astype(int)


array([ 17,  74,  43,  81,  72,  81, 122,  61,  89,  61])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
#(1,5,3)

np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [28]:
l = [1,2,3,4,-8,-10]
p = np.array(l,dtype = np.float32)
p[::-1]

array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [71]:
x = np.array([[1,2],[3,4]])
y = np.array([])
print(type(x) == type(y))
print('elements_count : {}'.format(x.size))

True
elements_count : 4


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [66]:
def softmax_function(a):
    if a.ndim != 1:
        raise Exception('Array is not 1D Please Convert it into 1D Array') 

    Eexpz = np.sum(np.exp(x))
    softmax_function_out = np.exp(x)/Eexpz
    return softmax_function_out

x = [86.03331084,37.7285648 ,48.64908087,87.16563062,38.40852563,37.20006318]

try:
    y = softmax_function(np.array(x))
except Exception as e:
    print(e) 
else:
    print(y)
finally:
    print('Good Buy...!')

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
Good Buy...!


In [82]:
a = (1,2)
b = (2,3)
np.vstack((a,b))

array([[1, 2],
       [2, 3]])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:

def vertical_stack(*args):
    # y = type(np.array([]))    
    for item in args:
        if type(item) == np.ndarray:
            pass
        else:
            raise Exception('Array is not Numpy array Please Convert it into Numpy Array') 

    return np.vstack(args)
        

a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
# a = [[0,1,2,3,4],[5,6,7,8,9]]

b = np.array([[1,1,1,1,1],[1,1,1,1,1]])

c= np.array([[0.10117373 ,0.1677244  ,0.73764059 ,0.83166097 ,0.48985695],
 [0.44581567 ,0.13502419 ,0.55692335 ,0.16479622 ,0.61193593]])

try:
    y = vertical_stack(a,b,c)
except Exception as e:
    print(e) 
else:
    print(y)
finally:
    print('Good Buy...!')

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
Good Buy...!


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [43]:
def date_array(start,end):
    x = start.split('-')
    y = end.split('-')
    output = []
    p = np.array(list(map(lambda x : int(x),x)))
    q = np.array(list(map(lambda x : int(x),y)))

    
    date = np.arange(p[2],q[2]+1)
    output = list(map(lambda z : ''.join('{}-{}-{}'.format(p[0],p[1],z)),date))
    return output

try:
    y = date_array(start = '2021-09-25', end = '2021-09-32')
except Exception as e:
    print(e) 
else:
    print(y)
finally:
    print('Good Buy...!')

['2021-9-25', '2021-9-26', '2021-9-27', '2021-9-28', '2021-9-29', '2021-9-30', '2021-9-31', '2021-9-32']
Good Buy...!


In [41]:
a = '5'
"{0:0=2d}".format(a)

ValueError: Unknown format code 'd' for object of type 'str'

###`Q-14:` Subtract the mean of each row from a matrix.

In [45]:
x = np.random.random((5,4))
y = x.mean(axis = 1,keepdims = True)
print(x)
print(y)
x-y#this will subtract a data from a Column



[[0.63949294 0.48414953 0.97875488 0.32225378]
 [0.86249952 0.85738724 0.33161481 0.68150885]
 [0.58535529 0.86079718 0.97449379 0.21359526]
 [0.78035475 0.99869004 0.44128706 0.76805944]
 [0.7382629  0.84442418 0.72582011 0.4277549 ]]
[[0.60616278]
 [0.6832526 ]
 [0.65856038]
 [0.74709782]
 [0.68406552]]


array([[ 0.03333016, -0.12201325,  0.3725921 , -0.283909  ],
       [ 0.17924691,  0.17413464, -0.3516378 , -0.00174375],
       [-0.07320509,  0.2022368 ,  0.31593341, -0.44496512],
       [ 0.03325692,  0.25159222, -0.30581076,  0.02096162],
       [ 0.05419738,  0.16035866,  0.04175459, -0.25631062]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

for i in range(x.shape[0]):
    for j in range(x.shape[1]-1):
       if j == 0:
            a = x[i][j]
            b = x[i][j+1]
            x[i][j] = b
            x[i][j+1] = a
            
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [46]:
a = np.arange(9).reshape(3,3)
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

for i in range(x.shape[0]):
    for j in range(x.shape[1]):
       if x[i][j]%2 != 0 :
           x[i][j] = -1
            
print(x)

[0 1 2 3 4 5 6 7 8 9]


IndexError: tuple index out of range

In [47]:
a = np.arange(10)
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [63]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

x = np.vstack((a,b))
np.max(x,axis = 0)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [64]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 756, 9079, 3002, 4539,  660],
       [5012,  705,  393,  941,   65],
       [6500, 9184, 2085, 6048, 7704],
       [3813, 4483, 9597, 8963,  860],
       [ 441, 4356, 1253, 3123, 7602],
       [7453, 3452, 8924, 6393, 8131],
       [9393, 7190, 8399, 6248, 8466],
       [3041, 5449, 4186, 2015, 3734]], dtype=int32)

In [75]:
#Code here

xmax = np.max(arr1)
xmin = np.min(arr1)

x = arr1[:,::2]
print(x)
x_normalised = (arr1 - xmin)/(xmax-xmin)
x_normalised

[[ 756 3002  660]
 [5012  393   65]
 [6500 2085 7704]
 [3813 9597  860]
 [ 441 1253 7602]
 [7453 8924 8131]
 [9393 8399 8466]
 [3041 4186 3734]]


array([[0.07249266, 0.94565674, 0.30812002, 0.46936634, 0.06242132],
       [0.51898867, 0.06714226, 0.03441041, 0.09190097, 0.        ],
       [0.67509442, 0.95667226, 0.21191775, 0.6276752 , 0.80140579],
       [0.39320185, 0.4634914 , 1.        , 0.9334872 , 0.08340327],
       [0.03944608, 0.45016786, 0.12463282, 0.3208141 , 0.79070499],
       [0.77507344, 0.35532942, 0.92939572, 0.66386907, 0.84620227],
       [0.97859841, 0.74748217, 0.87431809, 0.64865715, 0.88134704],
       [0.3122115 , 0.56483424, 0.43233319, 0.20457407, 0.38491397]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [50]:
def large_item(x,y):
    if y > len(x):
        raise Exception('Value of integer should be less then Lenth of the Array')
    x.sort()
    return x[-y]
arr = np.array([12,34,40,7,1,0])
n = 3
try:
    x = large_item(arr,1)
except Exception as e:
    print(e)
else:
    print(x)

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [52]:
a = np.array([1,2,3])
p = np.repeat(a,3)
q = np.tile(a,3)
np.hstack([p,q])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])