###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [2]:
import numpy as np

See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [75]:
x = np.random.randint(0,100,12).reshape(4,3)
x

array([[21, 90, 57],
       [55, 33, 46],
       [51, 77, 37],
       [76, 20, 14]], dtype=int32)

In [69]:
np.sort(x,axis = 1) #row vise

array([[21, 32, 36],
       [ 6, 40, 98],
       [20, 20, 54],
       [34, 57, 72]], dtype=int32)

In [70]:
x[x[:, 1].argsort()]

array([[54, 20, 20],
       [32, 21, 36],
       [72, 34, 57],
       [ 6, 98, 40]], dtype=int32)

In [76]:
np.array(sorted(x,key =lambda x : np.max(x)))

array([[55, 33, 46],
       [76, 20, 14],
       [51, 77, 37],
       [21, 90, 57]], dtype=int32)

In [78]:
np.sort(x,axis = None).reshape(4,3)

array([[14, 20, 21],
       [33, 37, 46],
       [51, 55, 57],
       [76, 77, 90]], dtype=int32)

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [94]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.expand_dims(np.array([41, 87, 72, 36, 92]), axis = 1)
x = np.concatenate((marks,extra_subject),axis = 1)

rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,5)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)
marks = np.concatenate((x,rec1,rec2),axis = 0)


sum_of_stud = marks.sum(axis = 1,keepdims = True)
marks = np.concatenate([marks,sum_of_stud],axis = 1)
marks

marks[:, -1].argsort()
marks[marks[:, -1].argsort()]

array([[ 13,  10,   9,  33,  41, 106],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 63,  46,  90,  42,  87, 328],
       [ 92,  71,  52,  61,  53, 329],
       [ 77,  83,  98,  95,  89, 442]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
arr = np.array([[1,2,3,4,5,6],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

np.unique(arr,axis = 0) #Unique Rows
np.unique(arr,axis = 1) #Unique Column

array([[1, 2, 3, 4, 5, 6],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 8, 8, 8],
       [1, 2, 3, 3, 1, 1]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [ ]:
arr = np.reshape(np.arange(25),(5,5))
print(arr)

print(np.flip(arr,axis= None))

# np.flip(np.flip(arr,axis = 0),axis = 1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [95]:
arr = np.array([[1,6,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

x = 6

# for item in range(len(arr)):
#     if x in arr[item]:
#         print(item)
        
np.where(np.any(arr>x,axis = 1) )       

(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [51]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [96]:
np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [ ]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr.shape)
print(np.max(arr),np.min(arr))
x = np.where(arr == np.max(arr))
y = np.where(arr == np.min(arr))
print(x,y)
z = np.delete(arr,[x,y],axis = 1)



(1, 200)
998 103
(array([0]), array([102])) (array([0]), array([66]))


True

In [100]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

max = arr.argmax()
min = arr.argmin()

print(arr.max(),arr.min())
arr = np.delete(arr,max,axis = 1)
arr = np.delete(arr,min,axis = 1)
print(arr.max(),arr.min())

998 103
997 117


In [25]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
np.delete(arr, [(0,1)],axis = 0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 9, 10, 11, 12]])

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [102]:
arr = np.random.randint(0, 1000, 200).reshape((50, 4))
x = np.clip(arr,a_min = 100,a_max = 200)

y = np.sort(x,axis = 0)

np.cumsum(y,axis = 0)

array([[ 100,  100,  100,  100],
       [ 200,  200,  200,  200],
       [ 300,  303,  300,  300],
       [ 400,  429,  400,  400],
       [ 500,  556,  500,  558],
       [ 600,  692,  600,  734],
       [ 713,  837,  707,  910],
       [ 872,  987,  835, 1088],
       [1072, 1145,  978, 1267],
       [1272, 1331, 1162, 1451],
       [1472, 1523, 1350, 1651],
       [1672, 1723, 1550, 1851],
       [1872, 1923, 1750, 2051],
       [2072, 2123, 1950, 2251],
       [2272, 2323, 2150, 2451],
       [2472, 2523, 2350, 2651],
       [2672, 2723, 2550, 2851],
       [2872, 2923, 2750, 3051],
       [3072, 3123, 2950, 3251],
       [3272, 3323, 3150, 3451],
       [3472, 3523, 3350, 3651],
       [3672, 3723, 3550, 3851],
       [3872, 3923, 3750, 4051],
       [4072, 4123, 3950, 4251],
       [4272, 4323, 4150, 4451],
       [4472, 4523, 4350, 4651],
       [4672, 4723, 4550, 4851],
       [4872, 4923, 4750, 5051],
       [5072, 5123, 4950, 5251],
       [5272, 5323, 5150, 5451],
       [54

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [44]:
arr = np.linspace(0, 1, 20).reshape((5, 4))
x = np.round(arr,decimals = 3)

min = np.min(x)
max = np.max(x)

print(min,max)

np.percentile(x,0) == min
np.percentile(x,100) == max

print(np.percentile(x,51)-np.percentile(x,50))

0.0 1.0
0.00988
